# https://guides.cocoapods.org/using/using-cocoapods.html
#
# Podfile and Podfile.lock should be kept under version control.
# Pods dir is also recommended.

source 'https://github.com/CocoaPods/Specs.git'
# source 'https://github.com/socialize/SocializeCocoaPods.git'

platform:ios, '8.0'
inhibit_all_warnings!

target "Carat" do
  pod 'AFNetworking', '~> 2.5'
  pod 'FBSDKCoreKit', '~> 4.9.1'
  pod 'FBSDKLoginKit', '~> 4.9.1'
  pod 'FBSDKShareKit', '~> 4.9.1'
  pod 'TwitterKit', '~> 1.15.1'
end

# pod 'Socialize', :podspec => 'https://raw.github.com/socialize/socialize-sdk-ios/master/Socialize.podspec'
# Append to your Podfile
post_install do |installer_representation|
	installer_representation.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
		end
	end
end
